# DB設定
spring.application.name=SpringBootSample
spring.datasource.url=jdbc:h2:~/health_check_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# DB初期化
spring.sql.init.encoding=UTF-8
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
# H2設定
spring.h2.console.enabled=true
# MyBatis設定
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
