# DB設定
spring.application.name=health-check-app
spring.datasource.url=jdbc:postgresql://localhost:5432/health_check_db
spring.datasource.username=postgress
spring.datasource.password=zawzaw555

# MyBatis
mybatis.mapper-locations=classpath*:mapper/postgres/*.xml
mybatis.type-aliases-package=com.zawzaw.healthcheck.*
mybatis.configuration.map-underscore-to-camel-case=true
